<a href="https://colab.research.google.com/github/omkar24102000/Anshul706/blob/main/Spam_Ham_BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd

In [64]:

messages = pd.read_csv(
    '/spam.csv',
    encoding='latin1'
)


In [65]:
messages = messages.rename(
    columns={
        'v1': 'label',
        'v2': 'message'
    }
)


In [66]:
messages = messages[['label', 'message']]

In [67]:
messages.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [68]:
## BOW, TFIDF, Machine learning

In [69]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [70]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [71]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [72]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2),binary=True)

In [73]:
#INDEPENDENT FEATURE
X = cv.fit_transform(corpus).toarray()

In [74]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [75]:
cv.vocabulary_

{'go': np.int64(823),
 'point': np.int64(1633),
 'crazi': np.int64(449),
 'avail': np.int64(122),
 'bugi': np.int64(226),
 'great': np.int64(870),
 'world': np.int64(2422),
 'la': np.int64(1103),
 'cine': np.int64(351),
 'got': np.int64(861),
 'wat': np.int64(2321),
 'ok': np.int64(1476),
 'lar': np.int64(1116),
 'joke': np.int64(1060),
 'wif': np.int64(2375),
 'oni': np.int64(1498),
 'ok lar': np.int64(1479),
 'free': np.int64(739),
 'entri': np.int64(616),
 'wkli': np.int64(2405),
 'comp': np.int64(402),
 'win': np.int64(2380),
 'cup': np.int64(463),
 'final': np.int64(696),
 'st': np.int64(1966),
 'may': np.int64(1268),
 'text': np.int64(2095),
 'receiv': np.int64(1720),
 'question': np.int64(1689),
 'std': np.int64(1982),
 'txt': np.int64(2200),
 'rate': np.int64(1701),
 'appli': np.int64(87),
 'free entri': np.int64(746),
 'entri wkli': np.int64(618),
 'wkli comp': np.int64(2406),
 'std txt': np.int64(1983),
 'txt rate': np.int64(2206),
 'rate appli': np.int64(1702),
 'dun': np.in

In [76]:
y = pd.get_dummies(messages['label'])


In [77]:
y

,ham,spam
0,True,False
1,True,False
2,False,True
3,True,False
4,True,False
...,...,...
5567,False,True
5568,True,False
5569,True,False
5570,True,False


In [78]:
y = y['ham'].astype(int).values

In [79]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [81]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)

In [82]:
from sklearn.metrics import confusion_matrix
confusion_m=confusion_matrix(y_test,y_pred)

In [83]:
confusion_m

array([[134,  16],
       [  6, 959]])

In [84]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [85]:
accuracy

0.9802690582959641